language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "bytekicker95-github"
    token:
      secure: "7219cd6743358e727e38b8f700fc0f587318bad1"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'