INSERT INTO usuario (nombre_usuario, clave, habilitado) VALUES ('analista1', '$2a$10$tOOoGe1Ai4rD1DvvOY2suee9UlU.8F7Yb7cCC4JyTz7H3WmYcTque', 1); #Contraseña 123456
INSERT INTO usuario (nombre_usuario, clave, habilitado) VALUES ('cajero1', '$2a$10$nHsulU/xwlLtoy0xp8LYGOJPG4aRVejMd/PR1D4c3HfvpHYu6F1XG', 1); #Contraseña 123456
INSERT INTO usuario (nombre_usuario, clave, habilitado) VALUES ('admin', '$2a$10$BZeRWsgzPCN2ShFPAfDrs.J5ms7K4qMG4BSxOfl3tiMtTY449M6la', 1); #Contraseña 123456
INSERT INTO rol (nombre, usuario_id) VALUES ('ROLE_ANALISTA', 1);
INSERT INTO rol (nombre, usuario_id) VALUES ('ROLE_CAJERO', 2);
INSERT INTO rol (nombre, usuario_id) VALUES ('ROLE_ANALISTA', 3);
INSERT INTO rol (nombre, usuario_id) VALUES ('ROLE_CAJERO', 3);
INSERT INTO persona (nombres, apellidos, dni, fecha_nacimiento, usuario_id) VALUES ('Juan', 'Perez', '12345678', '1990-05-09', 1);
INSERT INTO persona (nombres, apellidos, dni, fecha_nacimiento, usuario_id) VALUES ('Pedro', 'Gomez', '87654321', '1980-11-29', 2);
INSERT INTO persona (nombres, apellidos, dni, fecha_nacimiento, usuario_id) VALUES ('Jhonatan David', 'Castillo Salvador', '70009906', '1995-07-05', 3);
INSERT INTO persona (nombres, apellidos, dni, fecha_nacimiento) VALUES ('Ellen', 'Barajas Estrada', '43243213', '1987-08-13');
INSERT INTO persona (nombres, apellidos, dni, fecha_nacimiento) VALUES ('Ximena', 'Valdés Aguilera', '65465434', '2000-01-11');
INSERT INTO persona (nombres, apellidos, dni, fecha_nacimiento) VALUES ('Carlos', 'Casárez Tafoya', '79658321', '1990-11-25');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Velazco Vera', 'Jorge', '42146964', '1993-10-02');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Alva Campos', 'Victor', '40673760', '1947-02-11');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Arevalo Lopez', 'Javier', '43278119', '1993-07-09');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Arias Hernandez', 'Rosario', '45743257', '1946-01-23');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Arroyo Ramírez', 'Efraín', '41841665', '1997-09-13');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Alocen Barrera', 'Marco Tulio', '41980531', '1946-03-28');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Baiocchi Ureta', 'Cesar', '45460173', '1994-05-20');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Baylón Rojas', 'Isela Flor', '44925744', '1946-06-01');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Ramirez Acosta', 'Manuel', '31225741', '1944-01-01');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Silva Checa', 'Roberto', '46215922', '1993-03-12');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Loayza Alvarado', 'Lorenzo', '76544313', '1999-06-15');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Sanchez Loyola', 'Lucas', '32564146', '1944-09-01');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Reyes Acosta', 'Ricardo', '65542341', '1946-10-27');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Zuñiga Rodriguez', 'Angie', '76541321', '1994-11-01');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Villacorta Gomez', 'Luis', '79533156', '1995-05-25');
INSERT INTO persona(apellidos, nombres, dni, fecha_nacimiento) VALUES('Perez Aramayo', 'Fernanda', '35876248', '1945-04-15');
INSERT INTO cliente (ingresos_netos_mensuales, tipo_cliente, persona_id, gastos_fijos_mensuales) VALUES (3000.00, 'Dependiente', 1, 30.00);
INSERT INTO cliente (ingresos_netos_mensuales, tipo_cliente, persona_id, gastos_fijos_mensuales) VALUES (5000.00, 'Independiente', 2, 30.00);
INSERT INTO cliente (ingresos_netos_mensuales, tipo_cliente, persona_id, gastos_fijos_mensuales) VALUES (2000.00, 'Dependiente', 4, 20.00);
INSERT INTO cliente (ingresos_netos_mensuales, tipo_cliente, persona_id, gastos_fijos_mensuales) VALUES (6000.00, 'Independiente', 5, 40.00);
INSERT INTO cliente (ingresos_netos_mensuales, tipo_cliente, persona_id, gastos_fijos_mensuales) VALUES (7000.00, 'Dependiente', 6, 60.00);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(30,2000,'Independiente',7);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(40,2000,'Dependiente',8);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(20,1500,'Independiente',9);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(40,1500,'Independiente',10);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(20,1000,'Dependiente',11);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(30,1000,'Dependiente',12);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(50,1500,'Independiente',13);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(20,1500,'Dependiente',14);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(20,1500,'Independiente',15);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(30,1400,'Independiente',16);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(20,1000,'Dependiente',17);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(40,1000,'Dependiente',18);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(20,2000,'Independiente',19);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(30,2000,'Dependiente',20);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(40,1500,'Dependiente',21);
INSERT INTO cliente(gastos_fijos_mensuales, ingresos_netos_mensuales, tipo_cliente, persona_id) VALUES(50,1500,'Independiente',22);